"""empty message

Revision ID: 24f37c6884f0
Revises: d3f1efaaf522
Create Date: 2025-09-30 18:39:23.585493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24f37c6884f0'
down_revision = 'd3f1efaaf522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_description_enhanced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_recommendations_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('generated_by_ai_action_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ai_action_logs', ['generated_by_ai_action_id'], ['id'])

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_purchase_date'), ['purchase_date'], unique=False)

    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_suggested_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ai_price_confidence', sa.Float(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_language_preference', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ai_notification_preference', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_notification_preference')
        batch_op.drop_column('ai_language_preference')
        batch_op.drop_column('ai_enabled')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transaction_payment_status'))

    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.drop_column('ai_price_confidence')
        batch_op.drop_column('ai_suggested_price')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_purchase_date'))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('generated_by_ai_action_id')
        batch_op.drop_column('ai_recommendations')
        batch_op.drop_column('ai_insights')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('ai_recommendations_enabled')
        batch_op.drop_column('ai_description_enhanced')

    # ### end Alembic commands ###
