"""adds report table

Revision ID: 257db187d0af
Revises: 313eda81333a
Create Date: 2025-04-20 21:50:08.056211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257db187d0af'
down_revision = '313eda81333a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('total_tickets_sold', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_ticket_type_id'), ['ticket_type_id'], unique=False)

    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_type_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_type_event_id'))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_ticket_type_id'))
        batch_op.drop_index(batch_op.f('ix_report_event_id'))

    op.drop_table('report')
    # ### end Alembic commands ###
