"""updates

Revision ID: 31c9fb6f1f40
Revises: b427b3713070
Create Date: 2025-03-24 16:41:41.885853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c9fb6f1f40'
down_revision = 'b427b3713070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_ticket_merchant_request_id', ['merchant_request_id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_transaction_mpesa_receipt_number', ['mpesa_receipt_number'])
        batch_op.create_unique_constraint('uq_transaction_merchant_request_id', ['merchant_request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transaction_mpesa_receipt_number', type_='unique')
        batch_op.drop_constraint('uq_transaction_merchant_request_id', type_='unique')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('merchant_request_id')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ticket_merchant_request_id', type_='unique')
        batch_op.drop_column('merchant_request_id')

    # ### end Alembic commands ###
