"""Make password and phone_number optional, add OAuth fields

Revision ID: 3690526c297d
Revises: bd5c32661602
Create Date: 2025-03-28 00:06:50.464760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3690526c297d'
down_revision = 'bd5c32661602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_oauth', sa.Boolean(), nullable=True))
        batch_op.alter_column('password',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
        batch_op.alter_column('phone_number',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])  # Add constraint name

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_oauth')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
