"""Add featured column and event likes

Revision ID: 3e4e08441ff7
Revises: d5068df025b0
Create Date: 2025-04-25 18:33:47.625476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4e08441ff7'
down_revision = 'd5068df025b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # Remove the default value after the column is added
    op.alter_column('event', 'featured', server_default=None)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_transaction_ticket', 'ticket', ['ticket_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_ticket', type_='foreignkey')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('featured')

    op.drop_table('event_likes')
    # ### end Alembic commands ###
