"""Add scanned field to Ticket

Revision ID: 47d952d071d4
Revises: fb64464d8b3b
Create Date: 2025-02-23 17:22:34.501525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d952d071d4'
down_revision = 'fb64464d8b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('scanned',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('scanned',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
