"""removes repetition

Revision ID: 47fb351bae0c
Revises: 4d9399264cf8
Create Date: 2025-05-09 20:44:40.054094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fb351bae0c'
down_revision = '4d9399264cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer', schema=None) as batch_op:
        batch_op.drop_column('company_descriptions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_descriptions', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
