"""adds company description

Revision ID: 4d9399264cf8
Revises: 8cbf108d580a
Create Date: 2025-05-09 20:27:29.931348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9399264cf8'
down_revision = '8cbf108d580a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_descriptions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizer', schema=None) as batch_op:
        batch_op.drop_column('company_descriptions')

    # ### end Alembic commands ###
