"""Add unique constraint to transaction_id in ticket table

Revision ID: 82352834248b
Revises: 52998b1be333
Create Date: 2025-04-01 14:51:51.232150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82352834248b'
down_revision = '52998b1be333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_transaction_id', ['transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('unique_transaction_id', type_='unique')

    # ### end Alembic commands ###