"""adds payment status

Revision ID: 9e1728753100
Revises: 123b777e3c02
Create Date: 2025-04-17 10:50:33.050488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1728753100'
down_revision = '123b777e3c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('ticket', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'PAID', 'FAILED', 'REFUNDED', 'CANCELED', 'CHARGEBACK', 'ON_HOLD', name='paymentstatus'), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_transaction_ticket_id', 'ticket', ['ticket_id'], ['id'])
        batch_op.create_foreign_key('fk_transaction_user_id', 'user', ['user_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
