"""Update event table

Revision ID: a21902af5d86
Revises: 
Create Date: 2025-10-22 09:45:09.228932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a21902af5d86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_assisted_creation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_generated_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_from_draft_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_user_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_foreign_key(None, 'ai_event_drafts', ['created_from_draft_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('original_user_input')
        batch_op.drop_column('created_from_draft_id')
        batch_op.drop_column('ai_confidence_score')
        batch_op.drop_column('ai_generated_fields')
        batch_op.drop_column('ai_assisted_creation')

    # ### end Alembic commands ###
