"""Add AI description columns to Category

Revision ID: ad3702aab977
Revises: 24f37c6884f0
Create Date: 2025-10-05 14:52:38.869446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad3702aab977'
down_revision = '24f37c6884f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_action_logs_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_description_enhanced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_suggested_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('popularity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trending_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('trending_score')
        batch_op.drop_column('popularity_score')
        batch_op.drop_column('ai_suggested_keywords')
        batch_op.drop_column('ai_description_enhanced')

    with op.batch_alter_table('ai_action_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_action_logs_category_id'))
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
