"""Sync AI event copilot models

Revision ID: ae26ecd575c7
Revises: a21902af5d86
Create Date: 2025-10-22 10:22:18.209152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae26ecd575c7'
down_revision = 'a21902af5d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_event_drafts', schema=None) as batch_op:
        batch_op.drop_constraint('ai_event_drafts_published_event_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_event_drafts', schema=None) as batch_op:
        batch_op.create_foreign_key('ai_event_drafts_published_event_id_fkey', 'event', ['published_event_id'], ['id'])

    # ### end Alembic commands ###
