"""update tickettypeenum

Revision ID: b0a8ce134055
Revises: f6edac03d633
Create Date: 2025-02-21 11:28:01.938570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a8ce134055'
down_revision = 'f6edac03d633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('REGULAR', 'VIP', 'STUDENT', 'GROUP_OF_5', 'COUPLES', 'EARLY_BIRD', 'VVIP', 'GIVEAWAY', name='tickettypeenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_type', schema=None) as batch_op:
        batch_op.alter_column('type_name',
               existing_type=sa.Enum('REGULAR', 'VIP', 'STUDENT', 'GROUP_OF_5', 'COUPLES', 'EARLY_BIRD', 'VVIP', 'GIVEAWAY', name='tickettypeenum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
