"""Add payment_status to Ticket

Revision ID: b427b3713070
Revises: 6fd2343460a2
Create Date: 2025-03-20 16:29:19.280826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b427b3713070'
down_revision = '6fd2343460a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELED', 'CHARGEBACK', 'ON_HOLD', name='paymentstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
