"""more updates

Revision ID: c653d17dd267
Revises: 31c9fb6f1f40
Create Date: 2025-03-24 18:17:56.136264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c653d17dd267'
down_revision = '31c9fb6f1f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transaction_mpesa_receipt_number', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_transaction_mpesa_receipt_number', ['mpesa_receipt_number'])

    # ### end Alembic commands ###
