"""empty message

Revision ID: cb0e42190889
Revises: 3e4e08441ff7
Create Date: 2025-05-03 13:32:33.709555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0e42190889'
down_revision = '3e4e08441ff7'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
       DELETE FROM ticket
       WHERE transaction_id IS NULL OR qr_code IS NULL
       """)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('qr_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['qr_code'])
        batch_op.create_foreign_key(None, 'organizer', ['organizer_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_transaction_ticket', type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizer', ['organizer_id'], ['id'])
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_transaction_ticket', 'ticket', ['ticket_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('organizer_id')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('qr_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('organizer_id')

    # ### end Alembic commands ###
