"""Allow NULL for end_time

Revision ID: ceaff7762dc6
Revises: b0a8ce134055
Create Date: 2025-02-21 17:02:48.935330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaff7762dc6'
down_revision = 'b0a8ce134055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               nullable=False)

    # ### end Alembic commands ###
