"""empty message

Revision ID: dd97769e1b67
Revises: 7ff997ad2f01
Create Date: 2025-02-17 19:58:22.963526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd97769e1b67'
down_revision = '7ff997ad2f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
