"""add payment method attribute to transaction table

Revision ID: f6edac03d633
Revises: 1adfade6cd31
Create Date: 2025-02-21 02:44:26.992952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6edac03d633'
down_revision = '1adfade6cd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Enum('Mpesa', 'Paystack', name='payment_method_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
